default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock
  host: db

development:
  <<: *default
  database: food_data_api_development

test:
  <<: *default
  database: food_data_api_test

production:
  <<: *default
  database: food_data_api_production
  username: food_data_api
  password: <%= ENV["FOOD_DATA_API_DATABASE_PASSWORD"] %>
